// firstnames are from USA social society administration 'Top Names Over the Last 100 Years (1922-2021)' (https://www.ssa.gov/oact/babynames/decades/century.html)
// lastnames are from ThoughtCo 'Top 100 Most Common Last Names in the United States' (https://www.thoughtco.com/most-common-us-surnames-1422656)

export const firstNameList = ['James','Mary','Robert','Patricia','John','Jennifer','Michael','Linda','David','Elizabeth','William','Barbara','Richard','Susan','Joseph','Jessica','Thomas','Sarah','Charles','Karen','Christopher','Lisa','Daniel','Nancy','Matthew','Betty','Anthony','Margaret','Mark','Sandra','Donald','Ashley','Steven','Kimberly','Paul','Emily','Andrew','Donna','Joshua','Michelle','Kenneth','Carol','Kevin','Amanda','Brian','Dorothy','George','Melissa','Timothy','Deborah','Ronald','Stephanie','Edward','Rebecca','Jason','Sharon','Jeffrey','Laura','Ryan','Cynthia','Jacob','Kathleen','Gary','Amy','Nicholas','Angela','Eric','Shirley','Jonathan','Anna','Stephen','Brenda','Larry','Pamela','Justin','Emma','Scott','Nicole','Brandon','Helen','Benjamin','Samantha','Samuel','Katherine','Gregory','Christine','Alexander','Debra','Frank','Rachel','Patrick','Carolyn','Raymond','Janet','Jack','Catherine','Dennis','Maria','Jerry','Heather','Tyler','Diane','Aaron','Ruth','Jose','Julie','Adam','Olivia','Nathan','Joyce','Henry','Virginia','Douglas','Victoria','Zachary','Kelly','Peter','Lauren','Kyle','Christina','Ethan','Joan','Walter','Evelyn','Noah','Judith','Jeremy','Megan','Christian','Andrea','Keith','Cheryl','Roger','Hannah','Terry','Jacqueline','Gerald','Martha','Harold','Gloria','Sean','Teresa','Austin','Ann','Carl','Sara','Arthur','Madison','Lawrence','Frances','Dylan','Kathryn','Jesse','Janice','Jordan','Jean','Bryan','Abigail','Billy','Alice','Joe','Julia','Bruce','Judy','Gabriel','Sophia','Logan','Grace','Albert','Denise','Willie','Amber','Alan','Doris','Juan','Marilyn','Wayne','Danielle','Elijah','Beverly','Randy','Isabella','Roy','Theresa','Vincent','Diana','Ralph','Natalie','Eugene','Brittany','Russell','Charlotte','Bobby','Marie','Mason','Kayla','Philip','Alexis','Louis','Lori']
export const lastNameList = ['Smith','Johnson','Williams','Brown','Jones','Garcia','Miller','Davis','Rodriguez','Martinez','Hernandez','Lopez','Gonzales','Wilson','Anderson','Thomas','Taylor','Moore','Jackson','Martin','Lee','Perez','Thompson','White','Harris','Sanchez','Clark','Ramirez','Lewis','Robinson','Walker','Young','Allen','King','Wright','Scott','Torres','Nguyen','Hill','Flores','Green','Adams','Nelson','Baker','Hall','Rivera','Campbell','Mitchell','Carter','Roberts','Gomez','Phillips','Evans','Turner','Diaz','Parker','Cruz','Edwards','Collins','Reyes','Stewart','Morris','Morales','Murphy','Cook','Rogers','Gutierrez','Ortiz','Morgan','Cooper','Peterson','Bailey','Reed','Kelly','Howard','Ramos','Kim','Cox','Ward','Richardson','Watson','Brooks','Chavez','Wood','James','Bennet','Gray','Mendoza','Ruiz','Hughes','Price','Alvarez','Castillo','Sanders','Patel','Myers','Long','Ross','Foster','Jimenez']

// jobs are a mix from '25 Most Common Jobs in America' (https://www.indeed.com/career-advice/finding-a-job/most-common-jobs-in-america)
// and 'Top 100 Careers' (https://www.careerprofiles.info/top-100-careers.html)
export const jobList = ['Cashier','Food preparation worker','Stocking associate','Laborer','Janitor','Construction worker','Bookkeeper','Server','Medical assistant','Bartender','Administrative assistant','Marketing specialist','Police officer','Electrician','Mechanic','Retail sales associate','Customer service representative','Carpenter','Office clerk','Line supervisor','Truck Driver','Registered nurse','Software developer','Lawyer','Dentist','Pharmacist','Physician','Physical Therapist','Occupational Therapist','Veterinarian','Translator','Market Research Analyst','Financial Advisor','Accountant','Financial Manager','Public Relations Specialist','Insurance Agent','Receptionist','Housekeeper','Sales','Painter','Sports Coach'
]